#!/usr/bin/env bash

url=$1 
basename=${url##*/}
name=${2:-${basename%.*}}

mkdir $name
cd "$name"

git clone --recursive --bare "$url" .repo
echo "gitdir: ./.repo" > .git

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git worktree add main
