#!/usr/local/bin/bash

if [[ -f "$1" ]]; then
  [[ -n "$(command -v pbcopy)" ]] && pbcopy < "$1" && exit 0
  [[ -n "$(command -v xclip)" ]] && xclip < "$1" && exit 0
fi

[[ -n "$(command -v pbcopy)" ]] && echo "$1" | pbcopy && exit 0
[[ -n "$(command -v xclip)" ]] && echo "$1" | xclip && exit 0

