#!/usr/local/bin/bash

case "$1" in
  "") exec docker "$@" ;;
  b) shift; exec docker build "$@" ;;
  c) shift; exec docker compose "$@" ;;
  i) shift; exec docker image "$@" ;;
  n) shift; exec docker network "$@" ;;
  p) shift; exec docker container "$@" ;;
  ps) shift; exec docker ps -a ;;
  v) shift; exec docker volume "$@" ;;
  clean) exec docker rm "$(docker ps -aq)" ;;
  prune) exec docker system prune -af ;;
esac
