#!/usr/local/bin/bash

[[ -z "${CONTAINER_APP}" ]] && CONTAINER_APP=docker

case "$1" in
  -v|--volume)
    volume="$1" && shift
    name="$2" && shift
    exec ${CONTAINER_APP} run --rm -it -d -v "${volume}" -h "${name}" --name "${name}" "${name}" "$@"
    ;;
  *)
    name="$1" && shift
    exec ${CONTAINER_APP} run --rm -it -d -h "${name}" --name "${name}" "${name}" "$@"
    ;;
esac

